apiVersion: v1
kind: Service
metadata:
  name: llm-onnx
  namespace: llm-onnx
  labels:
    app: llm-onnx
    version: v1
    environment: local
spec:
  selector:
    app: llm-onnx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer