apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm
  namespace: llm
  labels:
    app: llm
    version: v1
    environment: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm
  template:
    metadata:
      labels:
        app: llm
    spec:
      containers:
      - name: llm-api
        image: llm-api
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"