apiVersion: v1
kind: Service
metadata:
  name: llm
  namespace: llm
  labels:
    app: llm
    version: v1
    environment: local
spec:
  selector:
    app: llm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer